name: Bug report
description: Create a report to help us improve
title: '[BUG]: '
labels: 'bug'
assignees: 'PierreJanineh'
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: description
    attributes:
      label: Describe the bug..
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce..
      description: Steps to reproduce the behavior?
      value: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour..
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: implementation
    attributes:
      label: How did you implement the package?
      options:
        - CocoaPods
        - Swift Package Manager (SPM)
    validations:
      required: true
  - type: checkboxes
    id: platform
    attributes:
      label: Which platforms does your app support?
      options:
        - iOS
        - macOS
        - macCatalyst
        - watchOS
        - tvOS
        - visionOS
    validations:
      required: true
  - type: input
    id: xcode
    attributes:
      label: What Xcode version do you use?
      placeholder: 16.0
    validations:
      required: true
