name: Bug report
description: Create a report to help us improve
title: 'BUG: '
labels: 'bug'
assignees: 'PierreJanineh'
body:
  - type: dropdown
    id: implementation
    attributes:
      label: How did you implement the package?
      options:
        - CocoaPods
        - Swift Package Manager (SPM)
    validations:
      required: true
