name: Feature request
description: Suggest an idea for this project
title: '[FEATURE REQUEST]: '
labels: 'enhancement'
assignees: 'PierreJanineh'
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you have considered.
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: true
